availableSecrets:
  secretManager:
    - versionName: 'projects/876748653486/secrets/quokka-secrets'

steps:
  # Build the custom container image
- name: 'gcr.io/cloud-builders/docker'
  secretEnv: ['SECRET_KEY=$$SECRET_KEY']
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/quokkaqr', '--build-arg', 'SECRET_KEY=$$SECRET_KEY', '.']
  # Push the custom container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/quokkaqr']
  # Deploy custom container image to Google Kubernetes Engine
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=quokka-engine.yaml
  - --image=gcr.io/$PROJECT_ID/quokkaqr
  - --location=us-west1
  - --cluster=quokka-engine
  - --namespace=quokka-qr-prod
