apiVersion: apps/v1
kind: Deployment
metadata:
  name: quokka-qr-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: quokka-qr-gke
        image: gcr.io/quokka-qr-project/quokkaqr:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
